version: '3'

services:
  ezxssdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPassword}
    volumes:
      - ./ezxssdb:/var/lib/mysql
  ezxss:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: partial
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/tmp/ezxss
    restart: always
    depends_on:
      - ezxssdb
