version: '3.7'

services:
  ezxssdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPassword}
    volumes:
      - ${dbDir}:/var/lib/mysql
  ezxss:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT:-80}:80"
      - "${TLSPORT:-443}:443"
    restart: always
    depends_on:
      - ezxssdb
